version: '3'
services:
  api:
    build: ./io-passthrough-api
    ports:
    - "3010:3010"
    links:
    - db
    - blockchain
    env_file:
    - io-passthrough-api/api.env
  db:
    build: ./mysqlDb
    ports:
    - "3306:3306"
    - "33060:33060"
    expose:
    - "3306"
    - "33060"
  blockchain:
    build: ./VoteManagerContract
    ports:
    - "8545:8545"
    expose:
    - "8545"
