version: '3'
services:
  api:
    build: ./io-passthrough-api
    ports:
    - "5000:5000"
    - "3010:3010"
    volumes:
    - ./io-passthrough-api/src
    links:
    - db
    - blockchain
    env_file:
    - api.env
  db:
    build: ./mysqlDb
    expose:
    - "3306"
    - "33060"
  blockchain:
    build: ./VoteManagerContract
    expose:
    - "8545"